version: '2.2'
services:
  es03-test:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: es03-test
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=testpass2020"
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - network.host=_local_,_site_
      - network.publish_host=INSTANCE-PUBLIC-IPV4
      - node.name=es03-test
      - node.master=true
      - node.data=true
      - http.port=9200
      - transport.port=9300
      - discovery.seed_hosts=es02-test,es01-test
      - cluster.initial_master_nodes=es01-test,es02-test,es03-test      
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data      
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    hostname: es03-test


  kb03-test:
    image: docker.elastic.co/kibana/kibana:7.6.0
    container_name: kb03-test
    volumes:      
      - /elastic-aws/es01/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5600:5600      
      - 5601:5601
    networks:
      - elastic    
    
volumes:
  data01:
  
networks:
    elastic:
      driver: bridge
      ipam:
        driver: default
        config:
        - subnet: 10.250.3.1/24
      