version: '2.2'
services:
  es02-test:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: es02-test
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=testpass2020"
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - network.host=_local_,_site_
      - network.publish_host=INSTANCE-PUBLIC-IPV4
      - node.name=es02-test
      - node.master=true
      - node.data=true
      - http.port=9200
      - transport.port=9300
      - discovery.seed_hosts=es01-test,es03-test
      - cluster.initial_master_nodes=es01-test,es02-test,es03-test
      - xpack.monitoring.collection.enabled=true    
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data      
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    extra_hosts:
      - "es01-test:ES01-PUBLIC-IP"
      - "es02-test:ES02-PUBLIC-IP"
      - "es03-test:ES03-PUBLIC-IP"
volumes:
  data01:
  
networks:
    elastic:
      driver: bridge
      ipam:
        driver: default
        config:
        - subnet: 10.250.2.1/24
      